// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace io.confluent.ksql.avro_schemas
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class KsqlDataSourceSchema : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"KsqlDataSourceSchema\",\"namespace\":\"io.confluent.ksql.avr" +
				"o_schemas\",\"fields\":[{\"name\":\"CREDIT_CARD_NBR\",\"type\":\"string\"},{\"name\":\"ATTEMPT" +
				"S\",\"type\":\"long\"}]}");
		private string _CREDIT_CARD_NBR;
		private long _ATTEMPTS;
		public virtual Schema Schema
		{
			get
			{
				return KsqlDataSourceSchema._SCHEMA;
			}
		}
		public string CREDIT_CARD_NBR
		{
			get
			{
				return this._CREDIT_CARD_NBR;
			}
			set
			{
				this._CREDIT_CARD_NBR = value;
			}
		}
		public long ATTEMPTS
		{
			get
			{
				return this._ATTEMPTS;
			}
			set
			{
				this._ATTEMPTS = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.CREDIT_CARD_NBR;
			case 1: return this.ATTEMPTS;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.CREDIT_CARD_NBR = (System.String)fieldValue; break;
			case 1: this.ATTEMPTS = (System.Int64)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
